#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""WPT_sim.sch - the version you can actually simulate in xschem.

TWO SCHEMATICS, AND THEY ARE NOT REDUNDANT.

  WPT.sch      the PDK cell version.  The receive coil is `ind_igzo`, which is
               what layout and LVS need.  It CANNOT be simulated with the
               coupling in it, because ngspice will not couple an inductor that
               lives inside a subcircuit:
                   Fatal error: k1: coupling to non-existent inductor xl1.l1

  WPT_sim.sch  this one.  Both coils drawn as a plain `ind.sym` in series with
               a `res.sym` - which is exactly what you did in the first place,
               and exactly why it works: `ind.sym` netlists as a bare L, so
               `K1 L1 L2 <k>` in a code block reaches it.  Open it in xschem,
               press simulate, and it runs.

`ind_igzo` IS an L in series with an R and nothing else - that is its whole
definition in design.ngspice - so the two schematics are the same circuit.
tb_wpt.py --check proves it by simulating both and comparing the current.

Every value comes from params.py, so editing that file and re-running this one
is how the schematic changes.
"""

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import params as P                                          # noqa: E402
import tb_wpt as T                                          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "WPT_sim.sch"))


def eng(x, unit=""):
    for scale, suf in ((1e-15, "f"), (1e-12, "p"), (1e-9, "n"), (1e-6, "u"),
                       (1e-3, "m"), (1.0, ""), (1e3, "k"), (1e6, "meg")):
        if abs(x) < scale * 1000:
            return "%.6g%s%s" % (x / scale, suf, unit)
    return "%.6g%s" % (x, unit)


def main():
    k = T.coupling_now() if P.K_OVERRIDE is None else P.K_OVERRIDE
    c_tx = P.tx_resonant_c()
    vamp = P.vamp_for_power()
    per = 1.0 / P.F_OP

    header = """v {{xschem version=3.4.8RC file_version=1.3

* WPT link, SIMULATABLE.  Generated by sim/make_sim_schematic.py - edit
* sim/params.py, not this file.
*
* Both coils are a plain inductor in series with a resistor, which is what
* lets K1 couple them: ngspice will not reach into a subcircuit, so the
* ind_igzo version in WPT.sch cannot carry the coupling.  Same circuit, two
* drawings - sim/tb_wpt.py --check compares them.
*
*   RX  {rxl} / {rxr} ohm   {rxdesc}
*   TX  {txl} / {txr} ohm   {txdesc}
*   k = {k:.6e} at {z} mm
*   TFTs W = {w:.0f}u, L = {l:.0f}u, ov = {ov:.0f}u
*   CTX = {ctx} series-tunes the transmit loop.  Without it the drive
*   current falls by about {ratio:.0f}x - it is not optional.
*
* To simulate: open in xschem, Simulation -> Netlist, then Simulate.
* The .control block below runs the AC sweep and a transient.
}}
G {{}}
K {{}}
V {{}}
S {{}}
E {{}}
""".format(rxl=eng(P.RX_L, "H"), rxr="%.1f" % P.RX_R,
           rxdesc="%s spiral, n=%d, w=%g um, gap=%g um, %g um Au"
                  % (P.RX_SHAPE, P.RX_N, P.RX_W_UM, P.RX_GAP_UM, P.RX_T_UM),
           txl=eng(P.TX_L, "H"), txr="%.3f" % P.TX_R,
           txdesc="%s, %g mm, %dt x %d, AWG %d"
                  % (P.TX_TOPOLOGY, P.TX_D_MM, P.TX_N, P.TX_LAYERS, P.TX_AWG),
           k=k, z=P.Z_MM, w=P.TFT_W * 1e6, l=P.TFT_L * 1e6, ov=P.TFT_OV * 1e6,
           ctx=eng(c_tx, "F"),
           ratio=2 * math.pi * P.F_OP * P.TX_L / P.TX_R)

    body = header

    # ---- wires ----------------------------------------------------------
    # LAYOUT.  The first version put the transmit coil at x = -10 and the
    # receive coil at x = -30 - twenty units apart - and the two halves of the
    # circuit drew on top of each other.  The netlist was right and the picture
    # was unreadable, which for a drawing whose whole purpose is to be looked
    # at is the same as being wrong.  The two loops now sit 250 units apart.
    #
    # Pin offsets: capa/res/ind/vsource are +-30 on the y axis from their
    # origin; tft_igzo is D(20,-30) G(-20,0) S(20,30), rotated with the symbol.
    #
    #   transmit  V1 (-700,70)-(-700,130)   R1 (-670,40)-(-610,40)
    #             CTX (-590,40)-(-530,40)   L2 (-480,70)-(-480,130)
    #             RTX (-480,160)-(-480,220)
    #   receive   L1 (-200,70)-(-200,130)   RRX (-200,-20)-(-200,40)
    #             C1 (-150,-60)-(-90,-60)
    #             M2 at (30,-40) rot 3 -> D (0,-60)  G (30,-20)  S (60,-60)
    #             M1 at (-60,150) rot 0 -> D (-40,120) G (-80,150) S (-40,180)
    #             C3 (200,70)-(200,130)     RL (320,70)-(320,130)
    wires = [
        # --- transmit loop, closed through RTX --------------------------
        (-700, 40, -700, 70), (-700, 40, -670, 40),
        (-610, 40, -590, 40),
        (-530, 40, -480, 40), (-480, 40, -480, 70),
        (-480, 130, -480, 160),
        (-480, 220, -700, 220), (-700, 130, -700, 220),
        # --- receive coil and its series resistance ---------------------
        (-200, 40, -200, 70),                  # RRX bottom to L1 top
        (-200, -60, -200, -20),                # RRX top to the rx node
        (-200, -60, -150, -60),                # rx into the DC block
        # --- the doubler node n1 ----------------------------------------
        (-90, -60, 0, -60),                    # C1 out to M2 drain
        (-40, -60, -40, 120),                  # n1 down to M1 drain
        (30, -20, -20, -20), (-20, -20, -20, -60),   # M2 gate back to n1
        (-80, 150, -80, 230),                  # M1 gate to ground
        (-40, 180, -40, 230),                  # M1 source to ground
        # --- the output --------------------------------------------------
        (60, -60, 200, -60), (200, -60, 200, 70),
        (200, -60, 320, -60), (320, -60, 320, 70),
        # --- the ground rail ---------------------------------------------
        (-200, 130, -200, 230), (-200, 230, -80, 230), (-80, 230, -40, 230),
        (-40, 230, 200, 230), (200, 130, 200, 230),
        (200, 230, 320, 230), (320, 130, 320, 230),
    ]
    for x1, y1, x2, y2 in wires:
        body += "N %d %d %d %d {}\n" % (x1, y1, x2, y2)

    # ---- components -----------------------------------------------------
    comps = [
        # --- receive: L in series with R, so K1 can reach the L ----------
        ("ind.sym", -200, 100, 0, 0,
         "name=L1\nm=1\nvalue=%s\nfootprint=1206\ndevice=inductor"
         % eng(P.RX_L)),
        ("res.sym", -200, 10, 0, 0,
         "name=RRX\nvalue=%s\nfootprint=1206\ndevice=resistor\nm=1"
         % eng(P.RX_R)),
        # --- the doubler -------------------------------------------------
        ("capa.sym", -120, -60, 1, 0,
         'name=C1\nm=1\nvalue=%s\nfootprint=1206\ndevice="ceramic capacitor"'
         % eng(P.C_RES)),
        ("symbols/tft_igzo.sym", -60, 150, 0, 0,
         "name=M1\nW=%.0fu\nL=%.0fu\nov=%.0fu\nnf=1\nm=1\nB=0\nb_scale=1\n"
         "model=igzo_tft\nspiceprefix=X"
         % (P.TFT_W * 1e6, P.TFT_L * 1e6, P.TFT_OV * 1e6)),
        ("symbols/tft_igzo.sym", 30, -40, 3, 0,
         "name=M2\nW=%.0fu\nL=%.0fu\nov=%.0fu\nnf=1\nm=1\nB=0\nb_scale=1\n"
         "model=igzo_tft\nspiceprefix=X"
         % (P.TFT_W * 1e6, P.TFT_L * 1e6, P.TFT_OV * 1e6)),
        ("capa.sym", 200, 100, 2, 0,
         'name=C3\nm=1\nvalue=%s\nfootprint=1206\ndevice="ceramic capacitor"'
         % eng(P.C_OUT)),
        ("res.sym", 320, 100, 0, 0,
         "name=RL\nvalue=%s\nfootprint=1206\ndevice=resistor\nm=1"
         % eng(P.R_LOAD)),
        # --- transmit ----------------------------------------------------
        ("vsource.sym", -700, 100, 0, 0,
         'name=V1 value="DC 0 AC 1 SIN(0 %s %s)" savecurrent=true'
         % (eng(vamp), eng(P.F_OP))),
        ("res.sym", -640, 40, 1, 0,
         "name=R1\nvalue=%s\nfootprint=1206\ndevice=resistor\nm=1"
         % eng(P.R_SRC)),
        ("capa.sym", -560, 40, 1, 0,
         'name=CTX\nm=1\nvalue=%s\nfootprint=1206\ndevice="ceramic capacitor"'
         % eng(c_tx)),
        ("ind.sym", -480, 100, 0, 0,
         "name=L2\nm=1\nvalue=%s\nfootprint=1206\ndevice=inductor"
         % eng(P.TX_L)),
        ("res.sym", -480, 190, 0, 0,
         "name=RTX\nvalue=%s\nfootprint=1206\ndevice=resistor\nm=1"
         % eng(P.TX_R)),
    ]
    for sym, x, y, rot, flip, props in comps:
        body += "C {%s} %d %d %d %d {%s\n}\n" % (sym, x, y, rot, flip, props)

    body += "C {devices/gnd.sym} -40 230 0 0 {name=g1 lab=0}\n"
    body += "C {devices/gnd.sym} -700 220 0 0 {name=g2 lab=0}\n"
    body += """C {devices/lab_pin.sym} 130 -60 0 1 {name=p1 sig_type=std_logic lab=out}
C {devices/lab_pin.sym} -200 -60 0 0 {name=p2 sig_type=std_logic lab=rx}
C {devices/lab_pin.sym} -60 -60 0 0 {name=p3 sig_type=std_logic lab=n1}
C {devices/lab_pin.sym} -700 40 0 0 {name=p4 sig_type=std_logic lab=tx}
"""

    body += """C {devices/code_shown.sym} -700 320 0 0 {name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::IGZO_MODELS/design.ngspice
.lib $::IGZO_MODELS/igzo_mmm_lab.ngspice %s
"}
""" % P.CORNER

    ctrl = """* THE COUPLING.  This is the line the whole second schematic exists for:
* L1 and L2 are plain inductors here, so K reaches them.  In WPT.sch the
* receive coil is the ind_igzo subcircuit and this line fails with
*     Fatal error: k1: coupling to non-existent inductor xl1.l1
K1 L1 L2 %.6f
*
* The output filter is %s into %s - a time constant of %.3g s against a
* %.3g s carrier period.  Starting from zero, the transient needs about
* %.0f carrier cycles to settle.  .ic starts it at the answer instead;
* remove the line to watch it charge.
.ic v(out)=%.6f
*
.control
save all
echo AC-sweep
ac dec 40 1e3 1e7
echo transient-%d-cycles
tran %.4g %.4g
meas tran vout_avg AVG v(out) from=%.4g to=%.4g
print vout_avg
.endc
""" % (k, eng(P.C_OUT, "F"), eng(P.R_LOAD, "ohm"), P.C_OUT * P.R_LOAD, per,
       5 * P.C_OUT * P.R_LOAD * P.F_OP, _seed_vout(), 40,
       per / 200, 40 * per, 20 * per, 40 * per)

    body += ('C {devices/code_shown.sym} -180 320 0 0 '
             '{name=NGSPICE only_toplevel=true\nvalue="\n%s"}\n' % ctrl)
    body += ('C {devices/title.sym} -700 560 0 0 '
             '{name=l5 author="UCI/INRF - MMM Lab"}\n')

    with open(OUT, "w") as fh:
        fh.write(body)
    print("wrote %s" % OUT)
    print("  k = %.6e at %g mm" % (k, P.Z_MM))
    print("  L1 = %s / %s   L2 = %s / %s"
          % (eng(P.RX_L, "H"), eng(P.RX_R, "ohm"), eng(P.TX_L, "H"),
             eng(P.TX_R, "ohm")))
    print("  CTX = %s, V1 = %s amplitude at %s"
          % (eng(c_tx, "F"), eng(vamp, "V"), eng(P.F_OP, "Hz")))
    print("  open it with:  xschem %s" % OUT)
    return 0


def _seed_vout():
    """The settled output, so the schematic's transient starts where it ends."""
    try:
        import json
        b = json.load(open(os.path.join(HERE, "bode_tran.json")))
        for r in b["fixed"]:
            if abs(r["f_hz"] - P.F_OP) / P.F_OP < 0.02 and r["settled"]:
                return r["vout"]
        return b["peak"]["vout"]
    except Exception:
        return 0.0


if __name__ == "__main__":
    sys.exit(main())
