#!/usr/bin/env python3
"""Write WPT.sch from the design the sweeps produced.

Follows the project's own rule that nothing holding a number is written by
hand twice: every value in the schematic comes from rx_coil.json, tx_coil.json
and rectifier.json, so the drawing cannot drift away from what was simulated.

WHAT THE ORIGINAL DRAWING WAS MISSING, and why each addition is needed rather
than decorative:

  no ground.  Not one gnd symbol, so the netlist had no node 0 and nothing
      could be simulated at all.
  C3's lower plate floating.  The output capacitor sits at (270,70) with its
      lower pin at (270,100); the ground rail runs at y=110 and no wire joined
      them.  One missing segment, and it disconnects the output filter.
  no load.  Efficiency is power out over power in, and an unloaded rectifier
      delivers zero at any coupling.  Nothing could be measured.
  no coupling.  Two inductors were drawn and never declared coupled, so the
      two halves of the circuit were electrically unrelated.
  no transmit tuning.  The transmit coil is 171 uH: at 500 kHz that is 539
      ohms of reactance against 11.6 of resistance, and untuned it throttles
      the drive current to a fiftieth of what the driver could deliver.

THE COUPLING CANNOT LIVE IN THIS SCHEMATIC, and that is a tool limit, not a
choice.  ngspice's K statement will not reach into a subcircuit, and ind_igzo
is one:

    Fatal error: k1: coupling to non-existent inductor xl1.l1.

So the schematic keeps ind_igzo - it is the PDK cell, and it is what the
layout and the LVS need - and the coupled simulation lives in the flat core,
sim/wpt_core.spice, which sim/tb_wpt.py checks is electrically identical.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "WPT.sch"))


def eng(x, unit=""):
    """SPICE engineering notation."""
    for scale, suf in ((1e-15, "f"), (1e-12, "p"), (1e-9, "n"), (1e-6, "u"),
                       (1e-3, "m"), (1.0, ""), (1e3, "k"), (1e6, "meg")):
        if abs(x) < scale * 1000:
            return "%.6g%s%s" % (x / scale, suf, unit)
    return "%.6g%s" % (x, unit)


HEADER = """v {{xschem version=3.4.8RC file_version=1.3

* WPT link - IGZO TFT voltage doubler on a planar receive coil.
* GENERATED by sim/make_wpt_schematic.py.  Edit that, not this.
*
* Receive coil   {rx_desc}
*                L = {rx_l}, R = {rx_r} ohm at {f} kHz, Q = {rx_q}
* Transmit coil  {tx_desc}
*                L = {tx_l}, R = {tx_r} ohm, Q = {tx_q}
* Coupling       k = {k} at {z} mm
* Rectifier      W = {w} um, L = {l} um, ov = {ov} um, both devices
* Load           {rload} ohm
*
* WHAT THIS CIRCUIT DOES, measured: {vout} V out for {pin} W in, an
* efficiency of {eta}.  That is not a working power link and the report says
* so at length; the schematic is here because it is the design that number
* belongs to.
*
* THE COUPLING IS NOT IN THIS FILE.  ngspice will not couple into a
* subcircuit, and ind_igzo is one - "coupling to non-existent inductor
* xl1.l1".  The coupled netlist is sim/wpt_core.spice, and sim/tb_wpt.py
* --check verifies the flat coils there are electrically the same thing.
}}
G {{}}
K {{}}
V {{}}
S {{}}
E {{}}
"""


def main():
    rx = json.load(open(os.path.join(HERE, "rx_coil.json")))
    tx = json.load(open(os.path.join(HERE, "tx_coil.json")))
    rec = json.load(open(os.path.join(HERE, "rectifier.json")))
    ch, ct, dz = rx["chosen"], tx["chosen"], rec["design"]
    worst = rec["worst"]

    l_rx, r_rx = ch["l_nh"] * 1e-9, ch["r_ac"]
    l_tx, r_tx = ct["l_h"], tx["chosen_link"]["r_ac"]
    f = tx["f_hz"]
    c_tx = 1.0 / ((2.0 * 3.141592653589793 * f) ** 2 * l_tx)
    c_res = max(rx["caps_f"])
    c_out = max(rx["caps_f"])

    body = HEADER.format(
        rx_desc="%s spiral, n=%d, w=%g um, gap=%g um, %g um Au"
                % (ch["shape"], ch["n"], ch["w_um"], ch["gap_um"], ch["t_um"]),
        rx_l=eng(l_rx, "H"), rx_r="%.1f" % r_rx, rx_q="%.5f" % ch["q"],
        tx_desc="%s, %d turns x %d layers, AWG %d (%.3f mm), former %g mm"
                % (ct["topology"], ct["n"], ct["layers"], ct["awg"],
                   ct["d_wire_mm"], ct["d_in_mm"]),
        tx_l=eng(l_tx, "H"), tx_r="%.3f" % r_tx,
        tx_q="%.1f" % tx["chosen_link"]["q"],
        k="%.4e" % tx["chosen_link"]["k"], z="%g" % tx["z_mm"],
        f="%.0f" % (f / 1e3),
        w="%.0f" % (dz["w"] * 1e6), l="%.0f" % (dz["l"] * 1e6),
        ov="%.0f" % (dz["ov"] * 1e6), rload="%.0f" % dz["rload"],
        vout="%.3f" % worst["vout"], pin="%.0f" % worst["pin"],
        eta="%.2e" % worst["eta"])

    wires = [
        # --- receive side, as originally drawn -------------------------
        (-30, 90, -30, 110), (-30, 110, 120, 110), (120, 110, 270, 110),
        (210, 0, 270, 0), (270, 0, 270, 40),
        (90, 0, 150, 0), (120, 0, 120, 50),
        (140, 40, 180, 40), (120, 40, 140, 40),
        (-30, 0, 30, 0), (-30, 0, -30, 30),
        (80, 80, 80, 110),
        # C3's lower plate to the ground rail - the segment that was missing
        (270, 100, 270, 110),
        # --- the load, from the output rail down to ground -------------
        (270, 0, 360, 0), (360, 0, 360, 40),
        (360, 100, 360, 110), (270, 110, 360, 110),
        # --- transmit side: source, source resistance, tuning, coil ----
        (-220, 10, -190, 10), (-220, 10, -220, 40),
        (-220, 90, -220, 120), (-220, 120, -100, 120), (-100, 90, -100, 120),
        (-130, 10, -100, 10), (-100, 10, -100, 30),
    ]
    for x1, y1, x2, y2 in wires:
        body += "N %d %d %d %d {}\n" % (x1, y1, x2, y2)

    comps = [
        # the receive coil: the PDK cell, with the values the search chose
        ("symbols/ind_igzo.sym", -30, 60, 0, 0,
         "name=L1\nls=%s\nrs=%.4g\nmodel=ind_igzo\nspiceprefix=X"
         % (eng(l_rx), r_rx)),
        # the doubler's DC block.  It is NOT a tuning element: at 10 uF its
        # reactance here is 32 milliohms against the coil's 497 ohms.
        ("capa.sym", 60, 0, 1, 0,
         'name=C1\nm=1\nvalue=%s\nfootprint=1206\ndevice="ceramic capacitor"'
         % eng(c_res)),
        ("symbols/tft_igzo.sym", 100, 80, 0, 0,
         "name=M1\nW=%.0fu\nL=%.0fu\nov=%.0fu\nnf=1\nm=1\nB=0\nb_scale=1\n"
         "model=igzo_tft\nspiceprefix=X"
         % (dz["w"] * 1e6, dz["l"] * 1e6, dz["ov"] * 1e6)),
        ("symbols/tft_igzo.sym", 180, 20, 3, 0,
         "name=M2\nW=%.0fu\nL=%.0fu\nov=%.0fu\nnf=1\nm=1\nB=0\nb_scale=1\n"
         "model=igzo_tft\nspiceprefix=X"
         % (dz["w"] * 1e6, dz["l"] * 1e6, dz["ov"] * 1e6)),
        ("capa.sym", 270, 70, 2, 0,
         'name=C3\nm=1\nvalue=%s\nfootprint=1206\ndevice="ceramic capacitor"'
         % eng(c_out)),
        # the load - new
        ("res.sym", 360, 70, 0, 0,
         "name=RL\nvalue=%s\nfootprint=1206\ndevice=resistor\nm=1"
         % eng(dz["rload"])),
        # transmit side
        # The amplitude is the one the sweeps were run at - the drive it takes
        # to get the rectifier over threshold at all.  eng(0.0) sat here first
        # and wrote a zero-amplitude source into the schematic.
        ("vsource.sym", -220, 60, 0, 0,
         "name=V1 value=\"DC 0 AC 1 SIN(0 %s %s)\" savecurrent=true"
         % (eng(worst["vamp"]), eng(f))),
        ("res.sym", -160, 10, 1, 0,
         "name=R1\nvalue=1\nfootprint=1206\ndevice=resistor\nm=1"),
        ("ind.sym", -100, 60, 0, 0,
         "name=L2\nm=1\nvalue=%s\nfootprint=1206\ndevice=inductor"
         % eng(l_tx)),
    ]
    for sym, x, y, rot, flip, props in comps:
        body += "C {%s} %d %d %d %d {%s\n}\n" % (sym, x, y, rot, flip, props)

    # grounds: the receive return rail and the transmitter's own return
    body += "C {devices/gnd.sym} 80 110 0 0 {name=g1 lab=0}\n"
    body += "C {devices/gnd.sym} -220 120 0 0 {name=g2 lab=0}\n"

    body += """C {devices/code_shown.sym} 60 200 0 0 {name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::IGZO_MODELS/design.ngspice
.lib $::IGZO_MODELS/igzo_mmm_lab.ngspice tt
"}
"""

    ctrl = """* The transmit loop MUST be series-tuned: L2 is %s and its reactance at
* %.0f kHz is %.0f ohms against %.2f ohms of resistance.  Untuned, the drive
* current - and with it everything downstream - falls by a factor of about %.0f.
CTX  n_txa n_tx1 %s
*
* THE COUPLING BELONGS HERE AND CANNOT GO HERE.  ngspice will not couple an
* inductor inside a subcircuit, and L1 above is the ind_igzo subcircuit:
*     Fatal error: k1: coupling to non-existent inductor xl1.l1
* The coupled netlist is sim/wpt_core.spice, generated from the same numbers.
* K1 L2 XL1.L1 %.6g
*
.control
set filetype=ascii
ac dec 40 1e3 1e7
tran %.4g %.4g
.endc
""" % (eng(l_tx, "H"), f / 1e3, 2 * 3.14159265 * f * l_tx, r_tx,
       2 * 3.14159265 * f * l_tx / r_tx, eng(c_tx),
       tx["chosen_link"]["k"], 1.0 / f / 200, 60.0 / f)

    body += 'C {devices/code_shown.sym} 340 200 0 0 {name=NGSPICE only_toplevel=true\nvalue="\n%s"}\n' % ctrl
    body += 'C {devices/title.sym} -220 390 0 0 {name=l5 author="UCI/INRF - MMM Lab"}\n'

    # DO NOT CLOBBER A HAND-EDITED DRAWING.  WPT.sch was edited by hand -
    # the receive coil swapped for a plain ind.sym so K1 could reach it,
    # labels added, the coupling uncommented - and an earlier version of this
    # guard looked for the generator's banner, which the edit had kept.  So it
    # passed, and the edits were overwritten.  The only reliable test is
    # whether the file on disk is byte-for-byte what this script would write.
    if os.path.exists(OUT) and "--force" not in sys.argv:
        if open(OUT).read() != body:
            print("REFUSING to overwrite %s" % OUT)
            print("  What is on disk is not what this script produces, so it")
            print("  has been edited since.  Your drawing wins by default.")
            print("  --force overwrites it; make_sim_schematic.py writes")
            print("  WPT_sim.sch instead and never touches this file.")
            return 2
    with open(OUT, "w") as fh:
        fh.write(body)
    print("wrote %s" % OUT)
    print("  L1  %s / %.1f ohm      (%s, n=%d, w=%g, gap=%g)"
          % (eng(l_rx), r_rx, ch["shape"], ch["n"], ch["w_um"], ch["gap_um"]))
    print("  L2  %s               (%s, %dt x %d, AWG%d)"
          % (eng(l_tx), ct["topology"], ct["n"], ct["layers"], ct["awg"]))
    print("  M1, M2  W=%.0fu L=%.0fu ov=%.0fu"
          % (dz["w"] * 1e6, dz["l"] * 1e6, dz["ov"] * 1e6))
    print("  C1 = C3 = %s, RL = %s, CTX = %s"
          % (eng(c_res), eng(dz["rload"]), eng(c_tx)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
