#!/usr/bin/env python3
"""The ngspice testbench for the whole link: transmitter, coupling, rectifier.

Renders a flat, parameterised netlist around the coils rx_coil.py and
tx_coil.py chose, runs ngspice in batch, and parses the AC sweep and the
transient into efficiency numbers.  Same shape as OPAM/sim/tb_common.py, which
is the pattern this project already uses.

THE CIRCUIT is the one drawn in WPT.sch: a Greinacher voltage doubler.  The
receive coil feeds a series capacitor; one diode-connected TFT clamps the
negative excursion, the second passes the positive one into the output
capacitor.  Two things WPT.sch does not have and this bench adds, because
without them there is no efficiency to speak of:

  - a load resistance.  Efficiency is power out over power in, and with no
    load the output power is zero at any coupling.
  - the coupling itself.  The schematic draws two inductors and never says
    they are coupled.

WHY THE COILS ARE FLAT L AND R RATHER THAN ind_igzo.  ngspice's K statement
couples two L elements, and ind_igzo is a .subckt with the L inside it.
Referencing it hierarchically is not portable.  The subcircuit is exactly an L
in series with an R - that is its whole definition in design.ngspice - so
writing those two elements directly loses nothing.  `--check` verifies that
claim by running the same testbench both ways.

THE DIODE-CONNECTED TFT.  A TFT has no bulk and its two channel terminals are
interchangeable, so a diode is made by tying the gate to one of them:

    XM1 vss vss n1   igzo_tft    conducts vss -> n1, clamping n1 upward
    XM2 n1  n1  out  igzo_tft    conducts n1  -> out

which is the doubler.  Both are drawn in WPT.sch the same way.
"""

import json
import math
import os
import re
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

NGSPICE = "/foss/tools/bin/ngspice"
PDK = "/foss/designs/TFT-MMM-LAB-PDK/libs.tech/ngspice"
HERE = os.path.dirname(os.path.abspath(__file__))

CORNERS = ("best", "tt", "all")

# The coils as two elements, and as the PDK subcircuit, for the --check run.
COILS_FLAT = """\
LTX  tx1 tx2 {l_tx}
RTX  tx2 0   {r_tx}
LRX  rx1 rx2 {l_rx}
RRX  rx2 0   {r_rx}
K1   LTX LRX {k}
"""

COILS_SUBCKT = """\
LTX  tx1 tx2 {l_tx}
RTX  tx2 0   {r_tx}
XLRX rx1 0   ind_igzo ls={l_rx} rs={r_rx}
LRX  nka nkb {l_rx}
RKA  nka 0   1e12
RKB  nkb 0   1e12
K1   LTX LRX {k}
"""

# Every optional element is ALWAYS present, with a value that makes it inert:
# a series capacitor defaults to 1 F (a short) and a shunt one to 1 aF (an
# open).  Splicing elements in as text left the netlist's node names depending
# on which experiment was running, which is how a "series capacitor" ended up
# connected between a node and itself.
NETLIST = """\
* WPT link - generated by tb_wpt.py, do not edit
.include {pdk}/design.ngspice
.lib {pdk}/igzo_mmm_lab.ngspice {corner}

.param f      = {f}
.param vamp   = {vamp}
.param rsrc   = {rsrc}
.param rload  = {rload}
.param cres   = {cres}
.param cout   = {cout}
.param ctx    = {ctx}
.param cprx   = {cprx}
.param ccpl   = {ccpl}
.param wtft   = {wtft}
.param ltft   = {ltft}
.param ovtft  = {ov}

* ---- transmitter -------------------------------------------------------
V1   src 0   DC 0 AC 1 SIN(0 'vamp' 'f')
RSRC src txa 'rsrc'
CTX  txa tx1 'ctx'          $ series tuning of the transmit loop; 1F = short

* ---- the two coils and their coupling ----------------------------------
{coils}

* ---- receive side: DC block, rectifier, load ---------------------------
CRES rx1 n1  'cres'         $ the doubler's DC block
CPRX rx1 0   'cprx'         $ shunt across the receive coil; 1aF = open
CCPL n1  0   'ccpl'         $ the coupling-capacitor experiment; 1aF = open
XM1  0   0   n1  igzo_tft W='wtft' L='ltft' ov='ovtft' nf=1
XM2  n1  n1  out igzo_tft W='wtft' L='ltft' ov='ovtft' nf=1
COUT out 0   'cout'
RL   out 0   'rload'

{analysis}
.end
"""

AC_BLOCK = """\
.control
set filetype=ascii
op
ac dec 40 {fmin} {fmax}
let pin  = -0.5*real(v(src)*conj(i(V1)))
let vrx  = mag(v(rx1))
let vo   = mag(v(out))
meas ac vrx_max MAX vrx
meas ac f_peak  WHEN vrx=vrx_max
meas ac vrx_at  FIND vrx AT={f}
meas ac vo_at   FIND vo  AT={f}
echo "@ACDONE"
.endc
"""

TRAN_BLOCK = """\
.ic v(out)={vout0}
.control
set filetype=ascii
tran {step} {stop} {start} {step}
let pin  = -v(src)*i(V1)
let pout = v(out)*v(out)/{rload}
meas tran pin_avg  AVG pin  from={t1} to={t2}
meas tran pout_avg AVG pout from={t1} to={t2}
meas tran vout_avg AVG v(out) from={t1} to={t2}
meas tran vout_max MAX v(out) from={t1} to={t2}
meas tran vout_min MIN v(out) from={t1} to={t2}
meas tran vout_e   FIND v(out) AT={t2}
meas tran vout_s   FIND v(out) AT={t1}
meas tran vrx_max  MAX v(rx1) from={t1} to={t2}
meas tran in_max   MAX pin from={t1} to={t2}
echo "@TRANDONE"
.endc
"""


def run(netlist, timeout=600):
    """One ngspice batch run.  Returns its stdout, stderr merged."""
    with tempfile.NamedTemporaryFile("w", suffix=".spice", delete=False,
                                     dir=HERE) as fh:
        fh.write(netlist)
        path = fh.name
    try:
        p = subprocess.run([NGSPICE, "-b", path], capture_output=True,
                           text=True, timeout=timeout)
        return p.stdout + "\n" + p.stderr
    except subprocess.TimeoutExpired:
        return "@TIMEOUT"
    finally:
        os.unlink(path)


MEAS_RE = re.compile(r"^\s*([a-z_0-9]+)\s*=\s*([-+0-9.eE]+)", re.M)


def measures(out):
    """Every `name = value` line ngspice's .meas produced."""
    d = {}
    for name, val in MEAS_RE.findall(out):
        try:
            d[name] = float(val)
        except ValueError:
            pass
    return d


def load_design():
    """The coils the two optimisers chose, in the units the netlist wants."""
    rx = json.load(open(os.path.join(HERE, "rx_coil.json")))
    tx = json.load(open(os.path.join(HERE, "tx_coil.json")))
    ch, ct = rx["chosen"], tx["chosen"]
    return {
        "f": tx["f_hz"],
        "l_rx": ch["l_nh"] * 1e-9, "r_rx": ch["r_ac"],
        "l_tx": ct["l_h"], "r_tx": tx["chosen_link"]["r_ac"],
        "k": tx["chosen_link"]["k"],
        # The series capacitor is a DC block, not a tuning element - the loop
        # is resistive, see rx_coil.regime() - so the choice among 1, 2 and
        # 10 uF is simply the lowest impedance, which is the largest value.
        "cres": max(rx["caps_f"]),
        "rx": rx, "tx": tx,
    }


SHORT_C = 1.0               # a capacitor big enough to be a wire
OPEN_C = 1e-18              # a capacitor small enough to be nothing


def build(d, corner="tt", analysis="", coils=COILS_FLAT, vamp=10.0, rsrc=1.0,
          rload=1e6, cout=10e-6, wtft=1000e-6, ltft=10e-6, ov=5e-6,
          cres=None, k=None, f=None, ctx=None, cprx=OPEN_C, ccpl=OPEN_C):
    """ctx defaults to the value that series-resonates the transmit loop.

    It is not an optional refinement.  The transmit coil is 171 uH, so at
    500 kHz its reactance is 539 ohms against 11.6 ohms of resistance: left
    untuned it limits the current to 18 mA and the driver delivers 2 mW of a
    requested 4 W.  Pass ctx=SHORT_C to see that happen.
    """
    f = f or d["f"]
    if ctx is None:
        ctx = tx_resonant_c(d, f)
    return NETLIST.format(
        pdk=PDK, corner=corner, f=f, vamp=vamp, rsrc=rsrc, rload=rload,
        cres=cres if cres is not None else d["cres"], cout=cout,
        wtft=wtft, ltft=ltft, ov=ov, ctx=ctx, cprx=cprx, ccpl=ccpl,
        coils=coils.format(l_tx=d["l_tx"], r_tx=d["r_tx"], l_rx=d["l_rx"],
                           r_rx=d["r_rx"], k=k if k is not None else d["k"]),
        analysis=analysis)


def tx_resonant_c(d, f=None):
    """The series capacitor that cancels the transmit coil's reactance."""
    f = f or d["f"]
    return 1.0 / ((2.0 * math.pi * f) ** 2 * d["l_tx"])


def ac(d, fmin=1e3, fmax=1e7, **kw):
    f = kw.get("f") or d["f"]
    nl = build(d, analysis=AC_BLOCK.format(fmin=fmin, fmax=fmax, f=f), **kw)
    out = run(nl)
    m = measures(out)
    return m, out


def transient(d, cycles_settle=40, cycles_meas=20, pts=200, vout0=0.0, **kw):
    """Steady-state transient.  Settles first, measures over whole cycles."""
    f = kw.get("f") or d["f"]
    per = 1.0 / f
    t1 = cycles_settle * per
    t2 = t1 + cycles_meas * per
    # ngspice's `meas ... FIND ... AT=` refuses the last point of the run
    # ("out of interval"), so the simulation goes one period past the window
    # it is measured over.
    nl = build(d, analysis=TRAN_BLOCK.format(
        step=per / pts, stop=t2 + per, start=0.0, t1=t1, t2=t2,
        rload=kw.get("rload", 1e6), vout0=vout0), **kw)
    out = run(nl)
    m = measures(out)
    if "pin_avg" in m and "pout_avg" in m and m["pin_avg"] > 0:
        m["eta"] = m["pout_avg"] / m["pin_avg"]
    # Has it actually settled?  The output is on a 10 uF capacitor, and the
    # measurement is meaningless if it is still charging.
    if "vout_s" in m and "vout_e" in m:
        span = abs(m["vout_e"] - m["vout_s"])
        ref = max(abs(m.get("vout_avg", 0.0)), 1e-12)
        m["drift_pct"] = 100.0 * span / ref
        m["settled"] = m["drift_pct"] < 1.0
    return m, out


def steady_state(d, cout=10e-6, rload=1e6, tries=6, **kw):
    """The rectifier's steady state, without simulating the settling.

    THE PROBLEM.  The output capacitor is 10 uF and the load is megohms, so the
    time constant is seconds while the carrier period is two microseconds.
    Simulating the charge-up honestly would mean millions of cycles.

    THE WAY ROUND IT.  The steady-state output is set by charge balance - what
    the diodes deliver per cycle equals what the load draws - and NOT by the
    capacitor, which only sets the ripple and the settling time.  So the value
    is found on a small capacitor, where it settles in tens of cycles, and then
    confirmed on the real one with .ic set to the answer: if it is the right
    answer the output does not move, and if it moves the run says so.

    Returns the confirming run's measurements, with the small-capacitor value
    under `vout_seed` and the ripple from the real capacitor.
    """
    # THE SEED CAPACITOR HAS TO SATISFY TWO INEQUALITIES, and getting them the
    # wrong way round is the whole trap.  Its time constant must be
    #   >> one carrier period, or it does not smooth and v(out) is the raw
    #      carrier - the first version sized it at tau = 0.1 us against a 2 us
    #      period and the "DC output" swung between -1.6 and +1.7 V;
    #   << the simulated span, or it has not settled by the end.
    # Twenty carrier periods sits between the two, and the settling window is
    # then five of those time constants.
    smooth_cycles = 20.0
    c_seed = smooth_cycles / (rload * d["f"]) if rload > 0 else 1e-12
    c_seed = max(min(c_seed, cout), 1e-15)
    settle_cycles = int(6 * smooth_cycles)
    v, seed = 0.0, None
    for _ in range(tries):
        m, _ = transient(d, cycles_settle=settle_cycles, cycles_meas=20,
                         cout=c_seed, rload=rload, vout0=v, **kw)
        new = m.get("vout_avg", 0.0)
        if seed is not None and abs(new - v) <= 1e-3 * max(abs(new), 1e-15):
            break
        v, seed = new, m
    m, out = transient(d, cycles_settle=20, cycles_meas=20, cout=cout,
                       rload=rload, vout0=v, **kw)
    m["vout_seed"] = v
    m["c_seed"] = c_seed
    return m, out


def traces(d, rload=1e4, vout0=0.0, cycles=6, pts=400, **kw):
    """The raw AC and transient vectors, for the report's figures.

    ngspice's `wrdata` writes plain columns, which is easier to trust than
    parsing a raw file: one file per analysis, one column per vector.

    The output files do NOT go next to this script.  `wrdata` takes its
    filename from the netlist text and splits it on whitespace, and this
    directory is under "MMM-LAB DESIGN" - so the path lost everything after
    the space and the file was never written, with no error anywhere.
    """
    import numpy as np
    f = kw.get("f") or d["f"]
    per = 1.0 / f
    tag = tempfile.mkdtemp(prefix="wpt_")
    ac_f = os.path.join(tag, "ac.dat")
    tr_f = os.path.join(tag, "tr.dat")
    block = """.ic v(out)={v0}
.control
set filetype=ascii
ac dec 60 1e3 1e7
let m = mag(v(rx1))
let p = 180/PI*cph(v(rx1))
wrdata {acf} m p
tran {step} {stop} {start} {step}
wrdata {trf} v(rx1) v(out)
echo "@DONE"
.endc
""".format(v0=vout0, acf=ac_f, trf=tr_f,
           step=per / pts, stop=(cycles + 1) * per, start=0.0)
    out = run(build(d, analysis=block, rload=rload, **kw))
    res = {}
    try:
        a = np.loadtxt(ac_f)
        res["f"] = a[:, 0]
        res["vrx_mag"] = a[:, 1]
        res["vrx_ph"] = a[:, 3]
        t = np.loadtxt(tr_f)
        res["t"] = t[:, 0] - t[0, 0]
        res["vrx"] = t[:, 1]
        res["vout"] = t[:, 3]
    except Exception as exc:
        res["error"] = "%s\n%s" % (exc, out[-1500:])
    finally:
        for fn in (ac_f, tr_f):
            if os.path.exists(fn):
                os.unlink(fn)
        os.rmdir(tag)
    return res


def check_coil_model(d):
    """The flat L+R against the PDK's ind_igzo subcircuit, same testbench."""
    print("The flat coil model against the PDK subcircuit.")
    print("ind_igzo is an L and an R in series and nothing else, so an AC")
    print("sweep of the receive branch must not know which one it is given.\n")
    ok = True
    nl = ("* ind_igzo vs L+R\n"
          ".include %s/design.ngspice\n"
          ".lib %s/igzo_mmm_lab.ngspice tt\n"
          "V1 a 0 AC 1\n"
          "LF a mf %g\nRF mf 0 %g\n"
          "V2 b 0 AC 1\n"
          "XS b 0 ind_igzo ls=%g rs=%g\n"
          ".control\nset filetype=ascii\n"
          "ac dec 20 1e3 1e7\n"
          # meas FIND takes a vector, not an expression - it silently produces
          # nothing at all when handed mag(i(V1)) directly.
          "let mf = mag(i(V1))\n"
          "let ms = mag(i(V2))\n"
          "meas ac if_1 FIND mf AT=1e5\n"
          "meas ac is_1 FIND ms AT=1e5\n"
          "meas ac if_2 FIND mf AT=1e6\n"
          "meas ac is_2 FIND ms AT=1e6\n"
          "echo \"@DONE\"\n.endc\n.end\n"
          % (PDK, PDK, d["l_rx"], d["r_rx"], d["l_rx"], d["r_rx"]))
    m = measures(run(nl))
    for a, b, f in (("if_1", "is_1", "100 kHz"), ("if_2", "is_2", "1 MHz")):
        if a not in m or b not in m:
            print("  %s: MISSING (%s)" % (f, sorted(m)))
            ok = False
            continue
        rel = abs(m[a] - m[b]) / abs(m[b]) if m[b] else 0.0
        good = rel < 1e-6
        ok = ok and good
        print("  %-8s flat |I| = %.8e   subckt |I| = %.8e   diff %.2e  %s"
              % (f, m[a], m[b], rel, "ok" if good else "FAIL"))
    print("\n%s" % ("IDENTICAL - the flat model is the subcircuit"
                    if ok else "THEY DIFFER - do not use the flat model"))
    return 0 if ok else 1


def main():
    d = load_design()
    print("The link as chosen:")
    print("  f       %.1f kHz" % (d["f"] / 1e3))
    print("  TX      L = %.3f uH, R = %.4f ohm" % (d["l_tx"] * 1e6, d["r_tx"]))
    print("  RX      L = %.2f nH, R = %.2f ohm" % (d["l_rx"] * 1e9, d["r_rx"]))
    print("  k       %.4e" % d["k"])
    print("  C_res   %g uF\n" % (d["cres"] * 1e6))

    m, out = ac(d)
    if "vrx_max" not in m:
        print("AC run produced no measurements:\n%s" % out[-2000:])
        return 1
    print("AC sweep:")
    print("  peak |v(rx)| = %.4e V at %.1f kHz  (predicted %.1f kHz)"
          % (m["vrx_max"], m.get("f_peak", 0) / 1e3, d["f"] / 1e3))
    print("  at %.1f kHz : |v(rx)| = %.4e V, |v(out)| = %.4e V"
          % (d["f"] / 1e3, m.get("vrx_at", 0), m.get("vo_at", 0)))

    mt, outt = steady_state(d)
    print("\nTransient (steady state):")
    for k_ in ("vout_avg", "vout_max", "vout_min", "pin_avg", "pout_avg",
               "eta", "drift_pct"):
        if k_ in mt:
            print("  %-10s %.6e" % (k_, mt[k_]))
    if not mt.get("settled", True):
        print("  NOT SETTLED - the output is still charging, %.1f%% drift"
              % mt.get("drift_pct", 0))
    return 0


if __name__ == "__main__":
    d_ = load_design()
    sys.exit(check_coil_model(d_) if "--check" in sys.argv else main())
