#!/usr/bin/env python3
"""Write wpt_core.spice: the whole link, flat, with the final numbers in it.

The bench (tb_wpt.py) builds this netlist in memory for every sweep point.
This writes one copy to disk with the design values baked in, so the link can
be run by hand - `ngspice -b wpt_core.spice` - without any Python in the way.
That matters: every number in the report comes out of the same template, and
this file is where somebody checks it by reading it.
"""

import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import rectifier as R                                       # noqa: E402
import tb_wpt as T                                          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    d = T.load_design()
    rec = json.load(open(os.path.join(HERE, "rectifier.json")))
    dz, worst = rec["design"], rec["worst"]
    f = d["f"]
    per = 1.0 / f

    analysis = """.ic v(out)={v0}
.control
set filetype=ascii
op
echo "--- AC: where the link peaks ---"
ac dec 40 1e3 1e7
let vrx = mag(v(rx1))
meas ac vrx_max MAX vrx
meas ac vrx_at  FIND vrx AT={f}
echo "--- transient: the steady state ---"
tran {step} {stop} 0 {step}
let pin  = -v(src)*i(V1)
let pout = v(out)*v(out)/{rload}
meas tran pin_avg  AVG pin  from={t1} to={t2}
meas tran pout_avg AVG pout from={t1} to={t2}
meas tran vout_avg AVG v(out) from={t1} to={t2}
meas tran vout_max MAX v(out) from={t1} to={t2}
meas tran vout_min MIN v(out) from={t1} to={t2}
let eff = pout_avg/pin_avg
print eff
.endc
""".format(v0=worst["vout"], f=f, step=per / 200,
           stop=42 * per, t1=20 * per, t2=40 * per, rload=dz["rload"])

    nl = T.build(d, corner="all", analysis=analysis,
                 vamp=worst["vamp"], rload=dz["rload"],
                 wtft=dz["w"], ltft=dz["l"], ov=dz["ov"], cout=10e-6)

    banner = """* ==========================================================================
* WPT link - IGZO TFT voltage doubler on a 1000 x 1000 um planar coil
*
* GENERATED by sim/wpt_core_gen.py from rx_coil.json, tx_coil.json and
* rectifier.json.  Every value here was chosen by a sweep; none was typed.
*
* Run it:   ngspice -b wpt_core.spice
*
* The transient starts from .ic v(out) = the steady state, because the output
* capacitor is 10 uF against a {rl:.0f} ohm load - a {tau:.2g} s time constant
* against a {per:.2g} s carrier period.  Simulating the charge-up honestly
* would take {cyc:.0e} cycles.  The steady state does not depend on the
* capacitor, only the ripple and the settling do, so it is found on a small
* capacitor and confirmed here.  See tb_wpt.steady_state().
*
* WHAT IT REPORTS: {vout:.3f} V into the load for {pin:.0f} W at the driver,
* which is an efficiency of {eta:.3g}.  Read the report before quoting that
* as a working link - it is four decades below anything useful, and the
* reason is the receive coil's Q of {q:.4f}, not the rectifier.
* ==========================================================================
""".format(rl=dz["rload"], tau=dz["rload"] * 10e-6, per=per,
           cyc=dz["rload"] * 10e-6 / per, vout=worst["vout"],
           pin=worst["pin"], eta=worst["eta"], q=d["rx"]["chosen"]["q"])

    out = os.path.join(HERE, "wpt_core.spice")
    with open(out, "w") as fh:
        fh.write(banner + nl.split("\n", 1)[1])
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
