v {xschem version=3.4.8RC file_version=1.3

* WPT link - IGZO TFT voltage doubler on a planar receive coil.
* GENERATED by sim/make_wpt_schematic.py.  Edit that, not this.
*
* Receive coil   square spiral, n=49, w=5 um, gap=5 um, 1 um Au
*                L = 1.01287uH, R = 497.4 ohm at 500 kHz, Q = 0.00640
* Transmit coil  solenoid, 50 turns x 2 layers, AWG 36 (0.127 mm), former 15 mm
*                L = 171.482uH, R = 10.574 ohm, Q = 50.9
* Coupling       k = 3.5840e-03 at 5 mm
* Rectifier      W = 6000 um, L = 5 um, ov = 2 um, both devices
* Load           10000 ohm
*
* WHAT THIS CIRCUIT DOES, measured: 0.801 V out for 858 W in, an
* efficiency of 7.49e-08.  That is not a working power link and the report says
* so at length; the schematic is here because it is the design that number
* belongs to.
*
* THE COUPLING IS NOT IN THIS FILE.  ngspice will not couple into a
* subcircuit, and ind_igzo is one - "coupling to non-existent inductor
* xl1.l1".  The coupled netlist is sim/wpt_core.spice, and sim/tb_wpt.py
* --check verifies the flat coils there are electrically the same thing.
}
G {}
K {}
V {}
S {}
E {}
N -30 90 -30 110 {}
N -30 110 120 110 {}
N 120 110 270 110 {}
N 210 0 270 0 {}
N 270 0 270 40 {}
N 90 0 150 0 {}
N 120 0 120 50 {}
N 140 40 180 40 {}
N 120 40 140 40 {}
N -30 0 30 0 {}
N -30 0 -30 30 {}
N 80 80 80 110 {}
N 270 100 270 110 {}
N 270 0 360 0 {}
N 360 0 360 40 {}
N 360 100 360 110 {}
N 270 110 360 110 {}
N -220 10 -190 10 {}
N -220 10 -220 40 {}
N -220 90 -220 120 {}
N -220 120 -100 120 {}
N -100 90 -100 120 {}
N -130 10 -100 10 {}
N -100 10 -100 30 {}
C {symbols/ind_igzo.sym} -30 60 0 0 {name=L1
ls=1.01287u
rs=497.4
model=ind_igzo
spiceprefix=X
}
C {capa.sym} 60 0 1 0 {name=C1
m=1
value=10u
footprint=1206
device="ceramic capacitor"
}
C {symbols/tft_igzo.sym} 100 80 0 0 {name=M1
W=6000u
L=5u
ov=2u
nf=1
m=1
B=0
b_scale=1
model=igzo_tft
spiceprefix=X
}
C {symbols/tft_igzo.sym} 180 20 3 0 {name=M2
W=6000u
L=5u
ov=2u
nf=1
m=1
B=0
b_scale=1
model=igzo_tft
spiceprefix=X
}
C {capa.sym} 270 70 2 0 {name=C3
m=1
value=10u
footprint=1206
device="ceramic capacitor"
}
C {res.sym} 360 70 0 0 {name=RL
value=10k
footprint=1206
device=resistor
m=1
}
C {vsource.sym} -220 60 0 0 {name=V1 value="DC 0 AC 1 SIN(0 152.145 500k)" savecurrent=true
}
C {res.sym} -160 10 1 0 {name=R1
value=1
footprint=1206
device=resistor
m=1
}
C {ind.sym} -100 60 0 0 {name=L2
m=1
value=171.482u
footprint=1206
device=inductor
}
C {devices/gnd.sym} 80 110 0 0 {name=g1 lab=0}
C {devices/gnd.sym} -220 120 0 0 {name=g2 lab=0}
C {devices/code_shown.sym} 60 200 0 0 {name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::IGZO_MODELS/design.ngspice
.lib $::IGZO_MODELS/igzo_mmm_lab.ngspice tt
"}
C {devices/code_shown.sym} 340 200 0 0 {name=NGSPICE only_toplevel=true
value="
* The transmit loop MUST be series-tuned: L2 is 171.482uH and its reactance at
* 500 kHz is 539 ohms against 10.57 ohms of resistance.  Untuned, the drive
* current - and with it everything downstream - falls by a factor of about 51.
CTX  n_txa n_tx1 590.855p
*
* THE COUPLING BELONGS HERE AND CANNOT GO HERE.  ngspice will not couple an
* inductor inside a subcircuit, and L1 above is the ind_igzo subcircuit:
*     Fatal error: k1: coupling to non-existent inductor xl1.l1
* The coupled netlist is sim/wpt_core.spice, generated from the same numbers.
* K1 L2 XL1.L1 0.00358402
*
.control
set filetype=ascii
ac dec 40 1e3 1e7
tran 1e-08 0.00012
.endc
"}
C {devices/title.sym} -220 390 0 0 {name=l5 author="UCI/INRF - MMM Lab"}
