v {xschem version=3.4.8RC file_version=1.3

* WPT link, SIMULATABLE.  Generated by sim/make_sim_schematic.py - edit
* sim/params.py, not this file.
*
* Both coils are a plain inductor in series with a resistor, which is what
* lets K1 couple them: ngspice will not reach into a subcircuit, so the
* ind_igzo version in WPT.sch cannot carry the coupling.  Same circuit, two
* drawings - sim/tb_wpt.py --check compares them.
*
*   RX  1.01287uH / 497.4 ohm   square spiral, n=49, w=5 um, gap=5 um, 1 um Au
*   TX  837.231nH / 0.808 ohm   solenoid, 1 mm, 8t x 4, AWG 36
*   k = 1.155195e-01 at 0.5 mm
*   TFTs W = 6000u, L = 10u, ov = 2u
*   CTX = 121.019nF series-tunes the transmit loop.  Without it the drive
*   current falls by about 3x - it is not optional.
*
* To simulate: open in xschem, Simulation -> Netlist, then Simulate.
* The .control block below runs the AC sweep and a transient.
}
G {}
K {}
V {}
S {}
E {}
N -700 40 -700 70 {}
N -700 40 -670 40 {}
N -610 40 -590 40 {}
N -530 40 -480 40 {}
N -480 40 -480 70 {}
N -480 130 -480 160 {}
N -480 220 -700 220 {}
N -700 130 -700 220 {}
N -200 40 -200 70 {}
N -200 -60 -200 -20 {}
N -200 -60 -150 -60 {}
N -90 -60 0 -60 {}
N -40 -60 -40 120 {}
N 30 -20 -20 -20 {}
N -20 -20 -20 -60 {}
N -80 150 -80 230 {}
N -40 180 -40 230 {}
N 60 -60 200 -60 {}
N 200 -60 200 70 {}
N 200 -60 320 -60 {}
N 320 -60 320 70 {}
N -200 130 -200 230 {}
N -200 230 -80 230 {}
N -80 230 -40 230 {}
N -40 230 200 230 {}
N 200 130 200 230 {}
N 200 230 320 230 {}
N 320 130 320 230 {}
C {ind.sym} -200 100 0 0 {name=L1
m=1
value=1.01287u
footprint=1206
device=inductor
}
C {res.sym} -200 10 0 0 {name=RRX
value=497.37
footprint=1206
device=resistor
m=1
}
C {capa.sym} -120 -60 1 0 {name=C1
m=1
value=10u
footprint=1206
device="ceramic capacitor"
}
C {symbols/tft_igzo.sym} -60 150 0 0 {name=M1
W=6000u
L=10u
ov=2u
nf=1
m=1
B=0
b_scale=1
model=igzo_tft
spiceprefix=X
}
C {symbols/tft_igzo.sym} 30 -40 3 0 {name=M2
W=6000u
L=10u
ov=2u
nf=1
m=1
B=0
b_scale=1
model=igzo_tft
spiceprefix=X
}
C {capa.sym} 200 100 2 0 {name=C3
m=1
value=10u
footprint=1206
device="ceramic capacitor"
}
C {res.sym} 320 100 0 0 {name=RL
value=10k
footprint=1206
device=resistor
m=1
}
C {vsource.sym} -700 100 0 0 {name=V1 value="DC 0 AC 1 SIN(0 60.1342 500k)" savecurrent=true
}
C {res.sym} -640 40 1 0 {name=R1
value=1
footprint=1206
device=resistor
m=1
}
C {capa.sym} -560 40 1 0 {name=CTX
m=1
value=121.019n
footprint=1206
device="ceramic capacitor"
}
C {ind.sym} -480 100 0 0 {name=L2
m=1
value=837.231n
footprint=1206
device=inductor
}
C {res.sym} -480 190 0 0 {name=RTX
value=808.06m
footprint=1206
device=resistor
m=1
}
C {devices/gnd.sym} -40 230 0 0 {name=g1 lab=0}
C {devices/gnd.sym} -700 220 0 0 {name=g2 lab=0}
C {devices/lab_pin.sym} 130 -60 0 1 {name=p1 sig_type=std_logic lab=out}
C {devices/lab_pin.sym} -200 -60 0 0 {name=p2 sig_type=std_logic lab=rx}
C {devices/lab_pin.sym} -60 -60 0 0 {name=p3 sig_type=std_logic lab=n1}
C {devices/lab_pin.sym} -700 40 0 0 {name=p4 sig_type=std_logic lab=tx}
C {devices/code_shown.sym} -700 320 0 0 {name=MODELS only_toplevel=true
format="tcleval( @value )"
value="
.include $::IGZO_MODELS/design.ngspice
.lib $::IGZO_MODELS/igzo_mmm_lab.ngspice tt
"}
C {devices/code_shown.sym} -180 320 0 0 {name=NGSPICE only_toplevel=true
value="
* THE COUPLING.  This is the line the whole second schematic exists for:
* L1 and L2 are plain inductors here, so K reaches them.  In WPT.sch the
* receive coil is the ind_igzo subcircuit and this line fails with
*     Fatal error: k1: coupling to non-existent inductor xl1.l1
K1 L1 L2 0.115520
*
* The output filter is 10uF into 10kohm - a time constant of 0.1 s against a
* 2e-06 s carrier period.  Starting from zero, the transient needs about
* 250000 carrier cycles to settle.  .ic starts it at the answer instead;
* remove the line to watch it charge.
.ic v(out)=6.949850
*
.control
save all
echo AC-sweep
ac dec 40 1e3 1e7
echo transient-40-cycles
tran 1e-08 8e-05
meas tran vout_avg AVG v(out) from=4e-05 to=8e-05
print vout_avg
.endc
"}
C {devices/title.sym} -700 560 0 0 {name=l5 author="UCI/INRF - MMM Lab"}
