#!/usr/bin/env python3
"""Generate the parameterised cores from the schematics themselves.

The cores used to carry hand-written node names, and that is a standing
invitation to drift: naming two anonymous nets in OPAM.sch renumbered the
rest, and every `net5` in the core silently meant something else.  Deriving
the core from the netlist xschem produces removes the hand-maintained copy.

What the core adds on top of the netlist is the parameterisation: each device
gets `W='<group>' L='<group>'` instead of a number, so the optimiser can move
a whole function at once.

    python3 make_core.py            # rewrites opam_core.spice, opam2_core.spice
"""

import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import apply_sizing as A

HERE = os.path.dirname(os.path.abspath(__file__))
DESIGN = os.path.dirname(HERE)

TFT = re.compile(r"^(XM\w+)\s+(\S+)\s+(\S+)\s+(\S+)\s+igzo_tft\s+W=(\S+)\s+L=(\S+)")
CAP = re.compile(r"^(XC\w+)\s+(\S+)\s+(\S+)\s+cap_mim\s+W=(\S+)\s+L=(\S+)")
RES = re.compile(r"^(R\w+)\s+(\S+)\s+(\S+)\s+(\S+)")

FIELD = """* Magnetic field, forwarded to every device so a sweep is a one-line change.
* The wrapper divides the intrinsic W by 1 + (mu*b_scale*B)^2, which - since
* level 1 only ever uses the product Kp*W/L - is the same as dividing Kp, i.e.
* the same as dividing the mobility.  That IS classical magnetoresistance;
* Kn and channel resistance are one fact, not two.  Contact resistance and
* overlap capacitance use the outer W and do not move with the field, which is
* where the physics leaves them too.
*
* b_gain is the hook for a measured effect: 1 means classical, and classical
* here is (mu*B)^2 = 2e-7 per tesla, which is not a sensor.
.param b_field = 0
.param b_gain  = 1"""

OPAM_HEADER = """* ==========================================================================
* OPAM - unipolar a-IGZO amplifier with cross-coupled pair and capacitor
* bootstrap load.  Topology after Zhao et al., IEEE TBCAS 18(6), 2024;
* device names follow MMM-LAB DESIGN/OPAM/OPAM.sch, not the paper's.
*
* GENERATED by sim/make_core.py from OPAM.sch - do not edit by hand.  Node
* names come from the schematic, so the two cannot disagree.
*
* Signal path:
*   INP/INN -> differential pair XM2/XM5, in parallel with the cross-coupled
*   pair XM3/XM4 (gate of one on the drain of the other: a negative
*   conductance that partly cancels the diode loads XM6/XM7)
*   -> the right branch XM18 -> bootstrap load XM19/XM20 + C2 -> follower
*   XM16 -> OUT, diode load XM15.  The left branch is the matched replica.
*
* BOOT_L / BOOT_R are the bootstrap gate nodes.  Level 1 has no subthreshold
* current, so XM14/XM20 leak exactly nothing and those nodes would have no DC
* path at all; Rb1/Rb2 stand in for the off-state channel and make the
* operating point a stated assumption instead of whatever the solver picks.
* At DC that leaves XM13/XM19 gate-tied to VDD - a diode load - while above
* the corner set by C1/C2 the capacitor holds their Vgs constant and they
* become current sources.  That is the trick of the paper.
* ==========================================================================

.param r_off = 1e12   $ off-state channel resistance of XM14 / XM20
""" + FIELD + """
.subckt OPAM VDD OUT INN INP BIAS VSS
"""

OPAM2_HEADER = """* ==========================================================================
* OPAM2 - all-enhancement IGZO TFT operational amplifier
* Topology after Zysset et al., IEEE EDL 34(11), 2013; device names follow
* MMM-LAB DESIGN/OPAM/OPAM2.sch, not the paper's numbering.
*
* GENERATED by sim/make_core.py from OPAM2.sch - do not edit by hand.
*
* Devices that must match share a parameter on purpose: the input pair, the
* two diode loads, the two common-mode sensing followers, and the two
* differential-to-single-ended followers.
*
* Multiplier m is folded into W: two devices of width W in parallel are
* exactly one device of width 2W in this wrapper (Rc goes as 1/W, Cov as W).
* ==========================================================================

""" + FIELD + """
.subckt OPAM2 VDD INP OUT INN VSS
"""

CAPS = {"XC1": "c_boot", "XC2": "c_boot", "XC3": "c_fb", "XC4": "c_fb"}


def netlist(sch):
    out = os.path.join(DESIGN, "simulation", sch)
    env = dict(os.environ, PDK_ROOT="/headless/pdks", PDK="TFT-MMM-LAB-PDK",
               DESIGNS="/foss/designs")
    os.makedirs(out, exist_ok=True)
    subprocess.run(["xschem", "-q", "-n", "-s", "-r", "--rcfile",
                    os.path.expanduser("~/.xschem/xschemrc"), "-o", out, sch],
                   cwd=DESIGN, env=env, capture_output=True)
    return os.path.join(out, sch.replace(".sch", ".spice"))


def build(sch, subckt, header, groups, out_name):
    """`sch` is the TESTBENCH: netlisting the cell on its own makes it the top
    level, and there is no .subckt block to read."""
    path = netlist(sch)
    inside, lines = False, []
    for raw in open(path):
        parts = raw.split()
        if parts[:1] == [".subckt"] and parts[1:2] == [subckt]:
            inside = True
            continue
        if inside and raw.startswith(".ends"):
            break
        if not inside:
            continue
        m = TFT.match(raw)
        if m:
            name, d, g, s, _, _ = m.groups()
            key = name[1:]                       # XM12 -> M12
            wk, lk = groups[key]
            lines.append("%-5s %-7s %-7s %-7s igzo_tft W='%s' L='%s' ov=5u nf=1"
                         " B='b_field' b_scale='b_gain'"
                         % (name, d, g, s, wk, lk))
            continue
        m = CAP.match(raw)
        if m:
            name, p, n, _, _ = m.groups()
            k = CAPS[name]
            lines.append("%-5s %-7s %-7s cap_mim W='%s' L='%s'" % (name, p, n, k, k))
            continue
        m = RES.match(raw)
        if m:
            name, p, n, _ = m.groups()
            lines.append("%-5s %-7s %-7s 'r_off'" % (name, p, n))

    text = header + "\n".join(lines) + "\n\n.ends %s\n" % subckt
    open(os.path.join(HERE, out_name), "w").write(text)
    print("wrote %s (%d devices)" % (out_name, len(lines)))


if __name__ == "__main__":
    build("test.sch", "OPAM", OPAM_HEADER, A.OPAM_GROUPS, "opam_core.spice")
    build("test2.sch", "OPAM2", OPAM2_HEADER, A.OPAM2_GROUPS, "opam2_core.spice")
