#!/usr/bin/env python3
"""
Generate an N-channel cross-coupled resonator netlist, in two return topologies.

SHARED (what the verified TEST1 design does): every channel's return branch ties
to the same node `actm`, so the N return inductors sit in parallel and the
effective return inductance is (L/2)/N.  That is what pushes the modes away from
1/(2*pi*sqrt(L*C)) and couples the channels to each other.

ISOLATED: each channel gets its own floating return node, coupled to the line
through its own capacitor, so the return inductance stays L/2 no matter how many
channels are populated.  Still ground-free, as the application requires.
"""

import argparse
import math
import os

# model paths resolve from this file, so the project can be moved or renamed
MODEL_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "test1", "models"))

# tank capacitance for a 10-channel 50-200 MHz plan on L = 100 nH
# (CALCUALTION/Resonator_C_10channels_50-200MHz.xlsx, L = 100 nH sheet)
LADDER_F = [50.0, 66.6667, 83.3333, 100.0, 116.6667,
            133.3333, 150.0, 166.6667, 183.3333, 200.0]
LADDER_C = [101.321, 56.9932, 36.4756, 25.3303, 18.61,
            14.2483, 11.2579, 9.11891, 7.53629, 6.33257]   # pF

ZCP = 10200.0        # coupling rule |Zcp| = 1/(2*pi*f*cp), fitted on A and B
ITAIL_100 = 0.65260  # mA, verified at 100 MHz
ITAIL_P = 3.15       # empirical exponent


def coupling_fF(f_mhz):
    return 1.0 / (2 * math.pi * f_mhz * 1e6 * ZCP) * 1e15


def itail_mA(f_mhz):
    return ITAIL_100 * (100.0 / f_mhz) ** ITAIL_P


def build(n, mode, L="100n", RS="1", model="NMOSGEN", w="100u", l="100u",
          orig=False, span=None, out_csv="OUTCSV", override=None):
    out = []
    a = out.append
    a("* auto-generated by scale/gen_nchan.py -- do not edit by hand")
    a(f"* N = {n} channels, return = {mode}, caps = "
      f"{'original' if orig else 'design ladder'}")
    a("VV4 VDD 0 'VDD'")
    a("VV3 n05 actm 0 AC 1")
    a("RR5 actp n05 1k m=1")
    if mode != "shared":
        # with an isolated return, actm reaches VDD only through capacitors;
        # a bias resistor gives it the DC path the solver needs (and that a real
        # ground-free implementation would need anyway)
        a("RRbias actm VDD 1meg m=1")

    caps, cps, its = [], [], []
    for k in range(n):
        if override:
            c, cp, it = override[k]
            caps.append(c); cps.append(cp); its.append(it)
            continue
        if orig:
            c, cp, it = [101.0, 70.0, 60.0, 101.0][k % 4], 400.0, 0.130
        else:
            f = LADDER_F[k % len(LADDER_F)]
            c, cp, it = LADDER_C[k % len(LADDER_C)], coupling_fF(f), itail_mA(f)
        caps.append(c); cps.append(cp); its.append(it)

    for k in range(n):
        nd, ns = f"nd{k}", f"ns{k}"
        a(f"* --- channel {k}: C = {caps[k]:.4f} pF, cp = {cps[k]:.2f} fF, "
          f"Itail = {its[k]:.5f} mA")
        cpk = cps[k] * (2 if mode != "shared" else 1)
        a(f"CCp{k} actp {nd} {cpk:.6g}f m=1")
        if mode == "shared":
            ret = "actm"
        else:
            ret = f"am{k}"
            # two caps in series must equal the shared-mode coupling, so each
            # one is doubled; otherwise the isolated variant is handicapped
            a(f"CCq{k} actm {ret} {2*cps[k]:.6g}f m=1")
        a(f"MMa{k} {nd} {ret} {ns} {ns} {model} w={w} l={l} m=1")
        a(f"MMb{k} {ret} {nd} {ns} {ns} {model} w={w} l={l} m=1")
        a(f"LLa{k} VDD xa{k} '{L}/2' m=1")
        a(f"RLa{k} xa{k} {nd} '{RS}/2' m=1")
        a(f"LLb{k} VDD xb{k} '{L}/2' m=1")
        a(f"RLb{k} xb{k} {ret} '{RS}/2' m=1")
        a(f"CCt{k} {ret} {nd} {caps[k]:.6g}p m=1")
        a(f"IIt{k} {ns} 0 {its[k]:.6g}m")

    a("")
    a(f".param VDD=1.5 L={L} RS={RS}")
    a(f".include {MODEL_DIR}/nmosgen_test1.lib")
    a(f".include {MODEL_DIR}/tft_igzo_test1.lib")
    a(span or ".ac lin 50000 35Meg 210Meg")
    a(".control")
    a("run")
    a("let vact = v(actp)-v(actm)")
    a(f"wrdata {out_csv} vact")
    a("quit")
    a(".endc")
    a(".end")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--n", type=int, default=2)
    p.add_argument("--return", dest="mode",
                   choices=("shared", "isolated"), default="shared")
    p.add_argument("--orig", action="store_true")
    p.add_argument("--model", default="NMOSGEN")
    p.add_argument("--w", default="100u")
    p.add_argument("--l", default="100u")
    p.add_argument("--RS", default="1")
    p.add_argument("--span", default=None)
    p.add_argument("--csv", default="OUTCSV")
    p.add_argument("--out", default=None)
    args = p.parse_args()
    txt = build(args.n, args.mode, RS=args.RS, model=args.model, w=args.w,
                l=args.l, orig=args.orig, span=args.span, out_csv=args.csv)
    (open(args.out, "w").write(txt) if args.out else print(txt))
